name: MyBB
markdown: kramdown
highlighter: rouge
category-list: [features]
permalink: pretty
url: https://mybb.com

collections:
  features:
    output: true
  rfcs:
    output: true
    permalink: /about/rfcs/:path/

sass:
  sass_dir: _sass
  style: compressed

gems:
  - jekyll-redirect-from
